# This file was generated by GoReleaser. DO NOT EDIT.
cask "arcflux" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "6129f6ed8571dc29366e442a9219a32b4092e753c935219c43be06106ea99d96"
      url "https://github.com/arcflux-ai/cli/releases/download/v#{version}/arcflux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2dd3c96839a3048e32727595aff8a3ded4b23f626227236f15ca4f5de3662d4"
      url "https://github.com/arcflux-ai/cli/releases/download/v#{version}/arcflux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d24d72ee7abdaa776da823c01d92b96c160fe81b10c9fd8f9417117c04d38d1c"
      url "https://github.com/arcflux-ai/cli/releases/download/v#{version}/arcflux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bf638e9cb887f6b2afd896817ca5d21c5c9a3606cdc65967e3af666d372d453"
      url "https://github.com/arcflux-ai/cli/releases/download/v#{version}/arcflux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "arcflux"
  desc "Trigger and manage Arcflux workflows from the terminal"
  homepage "https://docs.arcflux.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arcflux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arcflux"]
    end
  end

  # No zap stanza required

end
